package com.veronezzi.meusantinho.data.local.secure

import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyPermanentlyInvalidatedException
import android.security.keystore.KeyProperties
import java.security.GeneralSecurityException
import java.security.KeyStore
import java.security.UnrecoverableKeyException
import javax.crypto.AEADBadTagException
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

/**
 * Authenticated encryption of the picks file (ARCHITECTURE.md 5.2). Behind an interface so JVM
 * tests can use a software key; production uses [KeystoreBallotCipher].
 */
interface BallotCipher {
    /** Encrypts with a fresh IV. Returns the IV ([IV_SIZE] bytes) followed by ciphertext and tag. */
    fun encrypt(plaintext: ByteArray, associatedData: ByteArray): ByteArray

    /**
     * Inverse of [encrypt]. Throws [BallotKeyInvalidatedException] when the key is missing or was
     * permanently invalidated, and another [GeneralSecurityException] when the data was altered.
     */
    fun decrypt(sealed: ByteArray, associatedData: ByteArray): ByteArray

    /** Destroys the key: everything encrypted with it becomes unreadable. */
    fun deleteKey()

    companion object {
        const val IV_SIZE = 12
        const val TAG_BITS = 128
    }
}

/** The key is gone or permanently invalid, so data encrypted with it cannot be recovered. */
class BallotKeyInvalidatedException(cause: Throwable? = null) :
    GeneralSecurityException("Ballot key unavailable", cause)

/**
 * AES-256-GCM with a non-exportable key in AndroidKeyStore (alias [alias]). The key requires no
 * user authentication, so the optional app lock and the reminder stay independent of it, and it
 * is not StrongBox-backed (slow and unreliable on some devices; the TEE suffices here). The IV is
 * generated by the Keystore on every encryption (randomized encryption required).
 */
class KeystoreBallotCipher(private val alias: String = DEFAULT_ALIAS) : BallotCipher {
    private val lock = Any()

    override fun encrypt(plaintext: ByteArray, associatedData: ByteArray): ByteArray = synchronized(lock) {
        val cipher = Cipher.getInstance(TRANSFORMATION)
        try {
            cipher.init(Cipher.ENCRYPT_MODE, existingKey() ?: generateKey())
        } catch (e: KeyPermanentlyInvalidatedException) {
            throw BallotKeyInvalidatedException(e)
        }
        cipher.updateAAD(associatedData)
        val ciphertext = cipher.doFinal(plaintext)
        val iv = cipher.iv
        if (iv == null || iv.size != BallotCipher.IV_SIZE) throw GeneralSecurityException("Unexpected GCM IV")
        iv + ciphertext
    }

    override fun decrypt(sealed: ByteArray, associatedData: ByteArray): ByteArray = synchronized(lock) {
        if (sealed.size <= BallotCipher.IV_SIZE) throw AEADBadTagException("Truncated ballot data")
        val key = existingKey() ?: throw BallotKeyInvalidatedException()
        val cipher = Cipher.getInstance(TRANSFORMATION)
        try {
            cipher.init(Cipher.DECRYPT_MODE, key, GCMParameterSpec(BallotCipher.TAG_BITS, sealed, 0, BallotCipher.IV_SIZE))
        } catch (e: KeyPermanentlyInvalidatedException) {
            throw BallotKeyInvalidatedException(e)
        }
        cipher.updateAAD(associatedData)
        cipher.doFinal(sealed, BallotCipher.IV_SIZE, sealed.size - BallotCipher.IV_SIZE)
    }

    override fun deleteKey() {
        synchronized(lock) {
            try {
                keyStore().deleteEntry(alias)
            } catch (e: GeneralSecurityException) {
                // Nothing to delete, or the Keystore is unusable: either way the key is gone.
            }
        }
    }

    private fun keyStore(): KeyStore = KeyStore.getInstance(ANDROID_KEYSTORE).apply { load(null) }

    private fun existingKey(): SecretKey? = try {
        keyStore().getKey(alias, null) as? SecretKey
    } catch (e: UnrecoverableKeyException) {
        throw BallotKeyInvalidatedException(e)
    }

    private fun generateKey(): SecretKey {
        val spec = KeyGenParameterSpec.Builder(alias, KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT)
            .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
            .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
            .setKeySize(KEY_SIZE_BITS)
            .setRandomizedEncryptionRequired(true)
            .setUserAuthenticationRequired(false)
            .build()
        return KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, ANDROID_KEYSTORE).run {
            init(spec)
            generateKey()
        }
    }

    companion object {
        const val DEFAULT_ALIAS = "ballot_key_v1"
        private const val ANDROID_KEYSTORE = "AndroidKeyStore"
        private const val TRANSFORMATION = "AES/GCM/NoPadding"
        private const val KEY_SIZE_BITS = 256
    }
}
